### ISSUE TITLE
Incorrect README formatting on deno.land

### ISSUE THREAD

**Issue by JB1905** [denyncrawford/deno-figlet#2]
👋 Hi!
There are problems with README formatting on the https://deno.land/x/deno_figlet page (emoji and figlet result preview), checked on latest Firefox and Chrome:

![Screenshot_2020-07-25 deno_figlet Deno](https://user-images.githubusercontent.com/28870390/88461834-61916400-cea7-11ea-800f-493aab83216e.png)

**Comment by denyncrawford** [comment]
Hi thank you m8 :smile:! 

Thanks for letting me know, I saw your PR this morning. I can assume that the deno site does not support the github emoji format. Later at night I will work on it, but I guess you could make a commit in your PR fixing it :smiley: so I can merge it later.
